### ISSUE TITLE
Github pipeline till pythonanywhere

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noq_backend_python#11]
**Beskrivning**
Som frontendutvecklare vill jag ha tillgång till en uppdaterad backend på pythonanywhere 
så att jag kan testa api:erna över internet

**Acceptance Criteria**
Förutsatt att en pull request godkänns i backend på github
När koden godkänns och läggs in i main
Då uppdateras även pythonanywhere

**Subtasks**
+ STATIC_ROOT
+ ALLOWED_HOSTS
+CI pipeline -> pythonanywhere
+GH Action -> Web reload på pythonanywhere

**Definition of Done**
OK from wingmate
Code checked in
All subtasks done or cancelled

**Comment by Overath** [comment]
Hur går det här @elajth ?

**Comment by elajth** [comment]
Vi använder inte Python anywhere längre. Stänger denna
