### ISSUE TITLE
Add non random test user for user and host host group for easier testing.

### ISSUE THREAD

**Issue by jani-at-noq** [noQ-sweden/noq_backend_python#23]
###Beskrivning
Som en utvecklare behöver jag ha test data som inte ändrar sig när man genererar db innehåll.

###Acceptance Criteria
manage.py runscript generate_data generar två användare som är altid samma och har samma lösenord. En användare ska vara i grupp user and en i grupp host.

###Subtasks
None

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

Development Branch for backend: https://github.com/noQ-sweden/noq_backend_python/tree/366-inloggningssida

**Comment by SebbeKarner88** [comment]
Awesome! This will help alot! :)
